name: Deploy to ECR


on:
  push:
    branches:
      - testdeploy


jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: test
        run: |
          echo "secret: ${{ secrets.AWS_ACCOUNT_ID_${{ steps.extract_branch.outputs.branch }} }}"


      # - name: Set env variables
      #   run: |
      #     echo "REPOSITORY_URL=${{ secrets.AWS_ACCOUNT_ID_${{ steps.extract_branch.outputs.branch }} }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/ecs-tasks-tutorial" >> $GITHUB_ENV

      # - uses: actions/checkout@v2

      # - name: Build image
      #   run: |
      #     docker build -t $REPOSITORY_URL:latest ./app

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # - name: Get login password
      #   run: |
      #     aws ecr get-login-password \
      #     | docker login --username AWS --password-stdin $REPOSITORY_URL

      # - name: Push image
      #   run: |
      #     docker push $REPOSITORY_URL:latest
